default:
  image: python:3.11.5

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version
  - python -m venv .venv
  - source .venv/bin/activate
  - pip install pre-commit

check-code:
  script:
    - pre-commit run --all-files
  only:
    - merge_requests
