[tool.poetry]
name = "ignorem"
version = "0.1.0"
description = "Generate .gitignore file"
authors = ["Izzat Z. <izzat.zainir11@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.5"
pygobject = "3.46.0"
requests = "2.31.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.292"
black = "^23.9.1"
pre-commit = "^3.4.0"

[tool.poetry.group.typing.dependencies]
mypy = "^1.6.0"
types-requests = "^2.31.0.8"
pygobject-stubs = "^2.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
src = ["ignorem"]
fix = true
show-fixes = true
extend-select = [
    "N",    # pep8-naming
    "W",    # pycodestyle warning
    "I",    # isort
    "UP",   # pyupgrade
    "S",    # flake8-bandit
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
    "TCH",  # flake8-type-checking
    "TID",  # flake8-tidy-imports
]

[tool.ruff.isort]
case-sensitive = true
known-first-party = ["ignorem"]

[tool.mypy]
strict = true
explicit_package_bases = true

[[tool.mypy.overrides]]
module = [
    "ignorem.ui.page_preview",
    "ignorem.ui.page_search",
    "ignorem.ui.window_main"
]
disable_error_code = [
    "assignment",
    "method-assign",
    "truthy-function"
]
