[tool.poetry]
name = "ignorem"
version = "0.1.0"
description = ""
authors = ["Izzat Z. <izzat.zainir11@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pygobject = "^3.46.0"
requests = "^2.31.0"


[tool.poetry.group.dev.dependencies]
mypy = "^1.5.1"
ruff = "^0.0.290"
black = "^23.9.1"
isort = "^5.12.0"
pygobject-stubs = "^2.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
