APP_ID = "@APP_ID@"
APP_NAME = "@APP_NAME@"
APP_VERSION = "@APP_VERSION@"
APP_AUTHOR = "@APP_AUTHOR@"
APP_LICENSE = "@APP_LICENSE@"
APP_WEBSITE = "@APP_WEBSITE@"
APP_ISSUE_URL = "@APP_ISSUE_URL@"

REQUEST_TIMEOUT = 10  # in seconds
