stages:
  - lint

default:
  image: python:3.11.5

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"

cache:
  paths:
    - .cache/pip
    - .cache/pre-commit

before_script:
  - python --version ; pip --version
  - python -m venv .venv
  - source .venv/bin/activate
  - pip install pre-commit

check-all:
  stage: lint
  only:
    - merge_requests
    - develop
    - main
  script:
    - pre-commit run --all-files
